name=PY32LowPower
version=1.0.2
author=Regimantas Baublys <regtech0@gmail.com>
maintainer=Regimantas Baublys <regtech0@gmail.com>
sentence=A simple low-power library for the PY32F002A microcontroller.
paragraph=This library provides functions to easily manage sleep modes and wake-up events, making it ideal for low-power applications.
category=Device Control
url=https://github.com/regimantas/PY32LowPower
architectures=py32
